import Head from "next/head";
import Homepage from "./components/Home/Homepage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Standing Football</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </div>
  );
}
